# Generated by Django 6.0.6 on 2026-06-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_deporte', models.CharField(choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto'), ('voleibol', 'Voleibol'), ('tenis', 'Tenis'), ('microfutbol', 'Microfútbol'), ('otro', 'Otro')], max_length=20)),
                ('ubicacion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'db_table': 'cancha',
            },
        ),
        migrations.CreateModel(
            name='LogErrores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modulo_origen', models.CharField(max_length=100)),
                ('descripcion_error', models.TextField()),
                ('nivel_severidad', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='error', max_length=10)),
            ],
            options={
                'verbose_name': 'Log de Error',
                'verbose_name_plural': 'Log de Errores',
                'db_table': 'log_errores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('recepcionista', 'Recepcionista'), ('administrador', 'Administrador')], default='usuario', max_length=20)),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='reservas.cancha')),
            ],
            options={
                'verbose_name': 'Horario Disponible',
                'verbose_name_plural': 'Horarios Disponibles',
                'db_table': 'horario_disponible',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('no_asistida', 'No Asistida')], default='confirmada', max_length=15)),
                ('codigo_qr', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cancha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='PuntosHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('otorgado', 'Otorgado'), ('canjeado', 'Canjeado')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos', to='reservas.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_historial', to='reservas.usuario')),
            ],
            options={
                'verbose_name': 'Historial de Puntos',
                'verbose_name_plural': 'Historial de Puntos',
                'db_table': 'puntos_historial',
            },
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('cancha', 'fecha', 'hora_inicio', 'hora_fin'), name='unique_reserva_cancha_horario'),
        ),
    ]
