# Generated by Django 6.0.6 on 2026-06-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva_cancha_horario',
        ),
    ]
