# Generated by Django 6.0.6 on 2026-06-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_reserva_unique_reserva_cancha_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('no_asistida', 'No Asistida'), ('asistida', 'Asistida')], default='confirmada', max_length=15),
        ),
    ]
