# Generated by Django 6.0.4 on 2026-07-04 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_cancha_capacidad_y_tipo_personalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('bebida', 'Bebida'), ('snack', 'Snack'), ('otro', 'Otro')], max_length=20)),
                ('puntos_requeridos', models.PositiveIntegerField(help_text='Cantidad de puntos necesarios para canjear este producto.')),
                ('disponible', models.BooleanField(default=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Producto del Bar',
                'verbose_name_plural': 'Productos del Bar',
                'db_table': 'producto_bar',
                'ordering': ['categoria', 'puntos_requeridos'],
            },
        ),
        migrations.AlterModelOptions(
            name='configuracionpuntos',
            options={'verbose_name': 'Configuracion de Puntos', 'verbose_name_plural': 'Configuracion de Puntos'},
        ),
        migrations.RemoveField(
            model_name='configuracionpuntos',
            name='descripcion_beneficio',
        ),
        migrations.RemoveField(
            model_name='configuracionpuntos',
            name='minimo_canje',
        ),
        migrations.AlterField(
            model_name='horariodisponible',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='logerrores',
            name='nivel_severidad',
            field=models.CharField(choices=[('info', 'Informacion'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Critico')], default='error', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='lista_invitados',
            field=models.TextField(blank=True, help_text='Lista de nombres de los acompanantes (ej. Juan, Pedro, Luis)', null=True),
        ),
        migrations.CreateModel(
            name='CanjeProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_usados', models.PositiveIntegerField()),
                ('codigo', models.CharField(help_text='Codigo unico para presentar en el bar.', max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes_productos', to='reservas.usuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canjes', to='reservas.productobar')),
            ],
            options={
                'verbose_name': 'Canje de Producto',
                'verbose_name_plural': 'Canjes de Productos',
                'db_table': 'canje_producto',
                'ordering': ['-fecha'],
            },
        ),
    ]
